import { NextFunction, Request, Response, Router } from "express";
import { {{data.interface}} } from "@modules/{{data.model}}/{{data.model}}.model";
import { CrudManager } from "@managers/crud.manager";


/**
 * This is generated by Srishti Module Plugin
 * This is the abstracted business layer
 * Write all business rules and processing here
 * Crud Handling is done in Crud Managers
 * HTTP Handleing is done through routes
 * this would only hold the business rules
 */
export class {{data.interface}}Business
{

    public static Crud(req,res) 
    {
        console.log("Hello");
        res.send("Hi");         
        
    }
   
}
