import { NextFunction, Request, Response, Router } from "express";
import { {{data.interface}} } from "@modules/{{data.model}}/{{data.model}}.model";
import { {{data.interface}}Business } from "@modules/{{data.model}}/{{data.model}}.business";


/**
 * This is generated by Srishti Module Plugin
 * Srishti reccommends seperating the business logic
 * from the route handling. Here we created an route endpoint
 * but pass the processing back to the associated business layer
 * You can add more routes here. This sample handles most of the
 * CRUD operations
 */
export class {{data.routerName}}Routes
{

    public static create(router: Router) 
    {
         
        router.post("/{{data.model}}/:operation",  (req: Request, res: Response, next: NextFunction) => 
        {
            {{data.interface}}Business.Crud(req,res);     
        });

    }
   
}
