/** THIS FILE IS AUTOGENERATED BY ROUTE CONFIG PLUGIN
EDIITNG IS NOT RECCOMMENDED AND EVEN IF YOU EDIT NOTHING HAPPENS.
THE NEXT BUILD WOULD OVERWRITE IT */

import { AadharRoutes as Route0 } from '@routes/public-open/aadhar.api'

export class RouteManager
{
  public static CreateRouter(router){

      Route0.create(router);

} 
 }